### ISSUE TITLE
--force-ccd and --force-focal are no longer valid odm arguments

### ISSUE THREAD

**Issue by josephkoonce** [OpenDroneMap/CloudODM#7]
A month ago, I was able to use the following syntax for odm:
 ./odm images/NW031919NIR --force-ccd 6.2 --force-focal 5.4 --skip-3dmodel

Today, I tried another image directory and received an error message:

[/Volumes/Koonce4TB_Bkup/ODM ]  ./odm images/NW041719NIR --force-ccd 6.2 --force-focal 5.4 --skip-3dmodel
Invalid argument force-ccd. See ./odm args for a list of valid arguments.

On checking ./odm args, I find that neither --force-ccd nor --force-focal are listed as valid arguments, but last month the list of valid arguments was as follows:
--fast-orthophoto 
Skips dense reconstruction and 3D model generation. It generates an orthophoto directly from the sparse reconstruction. If you just need an orthophoto and do not need a full 3D model, turn on this option. Experimental.

--force-ccd <positive float>
Override the ccd width information for the images

--force-focal <positive float>
Override the focal length information for the images

--ignore-gsd 
Ignore Ground Sampling Distance (GSD). GSD caps the maximum resolution of image outputs and resizes images when necessary, resulting in faster processing and lower memory usage. Since GSD is an estimate, sometimes ignoring it can result in slightly better image output quality.

What has changed in the odm argument list?

**Comment by smathermather** [comment]
Looks like we have some updates to do here: https://docs.opendronemap.org/using.html#command-line-arguments on recent changes.

@Pierotofy — we should figure out a process in our code review for making sure docs stay up to date. Any thoughts on how we should do this? Maybe any pull request that doesn’t have a sibling pull request in docs needs to explain that there are no api changes?

Related: we may need to version docs... one for master and one for each release.

**Comment by smathermather** [comment]
But, the short answer to your question @josephkoonce is that we have been pushing API changes on master, which I understand is what runs on MasseranoLabs CloudODM instances. These are the pull requests in which this change occurred: https://github.com/OpenDroneMap/ODM/pull/957 & https://github.com/OpenDroneMap/ODM/pull/959, removing the above, as well as all of the ```--start-with``` ```--orthophoto-target-srs``` and ```--zip-results```. The rationale for most of these was that the flags either never or currently accomplished any task. One exception is the ```--use-fixed-camera-params``` flag which was removed but then restored in the subsequent https://github.com/OpenDroneMap/ODM/pull/961.

I haven't modified docs.opendronemap.org yet, as I'm unclear what version/branch we should be targeting. I'm tempted to suggest that until we have version of that, that it match master, since the official releases aren't mature enough yet relative to all the fixes in master.

**Comment by pierotofy** [comment]
So the reason those flags were removed is because they weren't doing anything (the flags were not changing the behavior of the program in any way). They must have served a purpose time ago, but when things changed (probably during a opensfm update) they weren't removed.

My take on docs is that we should automate the extraction of the command line parameters, or document them from the source code and extract the documentation for that part automatically as part of a build process.

I think until we hit the first `1.0` stable release the docs should document `master` (and we should keep everyone on a "rolling-release" method, just the way Arch Linux does it) until we reach stable. Then we should have docs for different versions.

**Comment by josephkoonce** [comment]
Thanks for the information.  I can confirm that the flags were not functioning.  I obtained the same ortho-images using only --skip-3Dmodel.  CloudODM generates the correct spatial scale without using the camera focal length and sensor width.  I guess that is part of the ODM "magic".  When I create individual GeoTiff images from the camera jpeg images, I have to specify the camera parameters and use the gps and altitude data from the jpeg EXIF metadata.
